apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-ci-cd
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-ci-cd
  template:
    metadata:
      labels:
        app: demo-ci-cd
    spec:
      serviceAccountName: demo-ci-cd-sa
      containers:
        - name: demo-ci-cd
          image: k3d-ysfregistry.localhost:5001/demo-ci-cd:1.0.2
          ports:
            - containerPort: 3000
          env:
            - name: VAULT_ADDR
              value: "http://vault.vault.svc:8200"
            - name: VAULT_ROLE
              value: "demo-ci-cd-role"

