apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-ci-cd
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-ci-cd
  template:
    metadata:
      labels:
        app: demo-ci-cd
    spec:
      containers:
        - name: demo-ci-cd
          image: k3d-ysfregistry.localhost:5001/demo-ci-cd:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
