apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps/demo-ci-cd/serviceaccount.yaml
  - apps/demo-ci-cd/deployment.yaml
  - apps/demo-ci-cd/service.yaml
  - apps/vault-db-demo/serviceaccount.yaml
  - apps/vault-db-demo/deployment.yaml
  - apps/vault-db-demo/service.yaml
  - vault/vault-auth-service-account.yaml
